### ISSUE TITLE
Add sort to TPTP variable printing

### ISSUE THREAD

**Issue by ZachJHansen** [potassco/anthem#21]
The spec language lets users write formulas like

forall X exists X$i q(X, X$i)

which in TPTP would currently be formatted ambiguously as

![X : $object] ( ?[X : $int]: ( q(X, X) ) )

which Vampire views as a syntax error. Instead, when formatting a variable named X with sort s in TPTP we should print Xs:

![Xg : $object] ( ?[Xi : $int]: ( q(Xg, Xi) ) )

**Comment by teiesti** [comment]
Fixed in #78.
