### ISSUE TITLE
Spec parsing

### ISSUE THREAD

**Issue by ZachJHansen** [potassco/anthem#22]
Currently the FOL grammar supports parsing and formatting everything up to and including theories. But we still need annotations for these formulas when we parse Anthem specifications or Anthem-P2P user guides. The following grammar rules should be added:

  predicate_signature = @{ predicate_symbol ~ "/" ~ (("0") | (ASCII_NONZERO_DIGIT ~ ASCII_DIGIT*)) }
   
  statement = { assumption | axiom | spec | lemma | input | output }
      assumption = { "assume:" ~ formula ~ "." }
      axiom      = { "axiom:" ~ formula ~ "." }
      spec       = { "spec:" ~ formula ~ "." }
      lemma      = { "lemma:" ~ formula ~ "." }
      input      = { "input:" ~ (placeholder | predicate_signature) ~ ("," ~ (placeholder | predicate_signature))* ~ "." }
      output     = { "output:" ~ (predicate_signature) ~ ("," ~ (predicate_signature))* ~ "." }
   
  specification = _{ SOI ~ statement* ~ EOI }

**Comment by teiesti** [comment]
Fixed in #85.
